---

- block:
  - name: Set output string variable value as a list item.
    set_fact:
      output_msg:
        - "User {{ simulation_json.item.user_name }} {{ simulation_json.stdout | from_json | community.general.json_query('EvaluationResults[0].EvalDecision') }} to {{ simulation_json.stdout | from_json | community.general.json_query('EvaluationResults[0].EvalActionName') }} on {{ simulation_json.stdout | from_json | community.general.json_query('EvaluationResults[0].EvalResourceName') }}."
    tags:
      - user

  # https://adminswerk.de/multi-line-string-yaml-ansible-I/
  # https://blog.crisp.se/2016/10/20/maxwenzin/how-to-append-to-lists-in-ansible
  - name: Concatenate output lists.
    set_fact:
      output_paragraph: "{{ output_paragraph + output_msg }}"
    tags:
      - user

  when: simulation_json.stdout | from_json | community.general.json_query('EvaluationResults[0].EvalDecision') == "allowed"
